
# Simple workflow for deploying static content to GitHub Pages
name: Reproduce results

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "30 9 * * 1"
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/fenics/dolfinx/dolfinx:v0.9.0

    steps:
      - uses: actions/checkout@v4

      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: cache_v1
          restore-keys: |
            cache_v1

      - name: Install dependencies
        run: python3 -m pip install .

      - name: Run simulation
        run: python3 reproduce_figures.py -n 1 -d 1 -o results

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./results
          if-no-files-found: error
